name: My first Workflow
# trigger
on:
- push

# Jobs in the workflow
jobs:
  # job name
  my-firts-workflow:
    # os that this workflow will be running on
    runs-on: ubuntu-latest

    #list of steps to perform task
    steps:
      - name: echo the date
        run: echo "The ccurrent time and date in Github is $(date)"
      - name: echo information aboubt the context
        run: echo "head_ref - ${{ github.head_ref }}, owner - ${{ github.repository_owner }}"
      - name: List runner name
        run: echo "runner os - ${{ runner.os }}"
